import type {
  Affectation,
  AnneeScolaire,
  EntityConfig,
  EntityName,
  Filiere,
  Formateur,
  Groupe,
  Module,
  Note,
  Presence,
  Stagiaire,
} from "@/types";

export const entityConfigs = {
  filieres: {
    title: "Filieres",
    description: "Organisez les parcours et specialites de formation.",
    endpoint: "/filieres",
    route: "/filieres",
    idKey: "idFiliere",
    queryKey: "filieres",
  } satisfies EntityConfig<Filiere>,
  groupes: {
    title: "Groupes",
    description: "Suivez les groupes, effectifs et filieres associees.",
    endpoint: "/groupes",
    route: "/groupes",
    idKey: "idGroupe",
    queryKey: "groupes",
  } satisfies EntityConfig<Groupe>,
  "annees-scolaires": {
    title: "Annees scolaires",
    description: "Gerez les periodes academiques.",
    endpoint: "/annees-scolaires",
    route: "/annees-scolaires",
    idKey: "idAnneeScolaire",
    queryKey: "annees-scolaires",
  } satisfies EntityConfig<AnneeScolaire>,
  formateurs: {
    title: "Formateurs",
    description: "Administrez les formateurs et leurs coordonnees.",
    endpoint: "/formateurs",
    route: "/formateurs",
    idKey: "idFormateur",
    queryKey: "formateurs",
  } satisfies EntityConfig<Formateur>,
  modules: {
    title: "Modules",
    description: "Configurez les modules et coefficients.",
    endpoint: "/modules",
    route: "/modules",
    idKey: "idModule",
    queryKey: "modules",
  } satisfies EntityConfig<Module>,
  stagiaires: {
    title: "Stagiaires",
    description: "Centralisez les informations des stagiaires.",
    endpoint: "/stagiaires",
    route: "/stagiaires",
    idKey: "idStagiaire",
    queryKey: "stagiaires",
  } satisfies EntityConfig<Stagiaire>,
  affectations: {
    title: "Affectations",
    description: "Affectez un module a un formateur, groupe et annee.",
    endpoint: "/affectations",
    route: "/affectations",
    idKey: "idAffectation",
    queryKey: "affectations",
  } satisfies EntityConfig<Affectation>,
  presences: {
    title: "Presences",
    description: "Enregistrez les presences, absences et retards.",
    endpoint: "/presences",
    route: "/presences",
    idKey: "idPresence",
    queryKey: "presences",
  } satisfies EntityConfig<Presence>,
  notes: {
    title: "Notes",
    description: "Saisissez les evaluations et notes des stagiaires.",
    endpoint: "/notes",
    route: "/notes",
    idKey: "idNote",
    queryKey: "notes",
  } satisfies EntityConfig<Note>,
} as const;

export const entityNames = Object.keys(entityConfigs) as EntityName[];
